name: GitHub Copilot Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  copilot-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: TypeScript type check
      run: bunx tsc --noEmit
      
    - name: Enable Copilot suggestions
      run: |
        echo "✅ Repository is configured for GitHub Copilot"
        echo "📋 Copilot instructions file: .github/copilot-instructions.md"
        echo "🎯 Project type: React Native/Expo with TypeScript"
        echo "🔧 Backend: Hono.js with tRPC"
        echo "💾 State: React Query + Zustand"
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const comment = `
          ## 🤖 GitHub Copilot Integration Active
          
          This repository is fully configured for GitHub Copilot with:
          
          - ✅ **Custom Instructions**: Tailored for React Native/Expo + TypeScript
          - ✅ **Type Safety**: tRPC integration for end-to-end type safety
          - ✅ **Best Practices**: Mobile development patterns and conventions
          - ✅ **Architecture Guidance**: Hono.js backend, React Query + Zustand state management
          
          Copilot will now provide context-aware suggestions based on this project's specific architecture and conventions.
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });